/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 question.gltf --transform 
Files: question.gltf [30.94KB] > C:\Users\User\Desktop\question\question-transformed.glb [15.04KB] (51%)
Author: UL (https://sketchfab.com/unmanned.lifemail)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/question-mark-e0969716da6c4168a1d98067be48769a
Title: question mark
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/question-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Digital_blue_2} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/question-transformed.glb')
